server:
  port: 9002
spring:
  application:
    name: easygo-admin-web
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.108:9001/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: easygo-admin-web-9002
FILE_SERVER_URL: http://192.168.1.120:8080/