server:
  port: 9005
spring:
  application:
    name: easygo-protal-web
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true
  redis:
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-total: 20
    hostName: 192.168.1.120
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.108:9001/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: easygo-protal-web-9005
salt: JavaNz
cas:
  casServerUrlPrefix: http://192.168.1.108:9999/cas
  #CAS服务器的登录地址 http://192.168.1.108:9999
  casServerLoginUrl: ${cas.casServerUrlPrefix}/login
  # CAS服务器注销的时候退出的地址，退出之后自动跳转位置 http://www.baidu.com,目前不可以，需要修改CAS服务器一个配置才可以
  casServerLogoutUrl: ${cas.casServerUrlPrefix}/logout?service=http://127.0.0.1:9005/member_login
  # cas和Shiro整合的一个过滤器名字 写死
  casFilterUrlPattern: /shiro-cas
  # 当前这个的服务器访问地址
  localServerUrlPrefix: http://localhost:${server.port}
  # 当前服务器登录地址，登录成功之后，还要跳转回来本地服务器
  localServerLoginUrl: ${cas.casServerLoginUrl}?service=${cas.localServerUrlPrefix}${cas.casFilterUrlPattern}