server:
  port: 9005
spring:
  application:
    name: easygo-protal-web
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true
  redis:
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-total: 20
    hostName: 192.168.1.120
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.108:9001/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: easygo-protal-web-9005
salt: JavaNz